<?php

use App\AI\Providers\GeminiProvider;
use App\AI\Providers\GroqProvider;
use App\AI\Providers\OllamaProvider;
use App\AI\Providers\OpenAiProvider;
use App\AI\Providers\OpenRouterProvider;

return [
    'enabled' => env('AI_ENABLED', false),
    'maintenance_mode' => env('AI_MAINTENANCE_MODE', false),
    'paid_fallback_allowed' => env('AI_PAID_FALLBACK_ALLOWED', false),
    'local_first' => env('AI_LOCAL_FIRST', false),
    'rag_enabled' => env('RAG_ENABLED', true),
    'semantic_search_enabled' => env('SEMANTIC_SEARCH_ENABLED', false),
    'semantic_grading_enabled' => env('AI_SEMANTIC_GRADING_ENABLED', false),
    'vision_enabled' => env('AI_VISION_ENABLED', false),
    'external_retrieval_enabled' => env('AI_EXTERNAL_RETRIEVAL_ENABLED', false),
    'supplemental_knowledge_enabled' => env('AI_SUPPLEMENTAL_KNOWLEDGE_ENABLED', false),
    'timeout_seconds' => (int) env('AI_REQUEST_TIMEOUT', 25),
    'connect_timeout_seconds' => (int) env('AI_CONNECT_TIMEOUT', 4),
    'max_requests_per_user_per_day' => (int) env('AI_MAX_REQUESTS_PER_USER_PER_DAY', 30),
    'cooldown_seconds' => (int) env('AI_TUTOR_COOLDOWN_SECONDS', 3),
    'circuit_failure_threshold' => (int) env('AI_CIRCUIT_FAILURE_THRESHOLD', 3),
    'circuit_cooldown_seconds' => (int) env('AI_CIRCUIT_COOLDOWN_SECONDS', 120),
    'daily_budget_usd' => (float) env('AI_DAILY_BUDGET_USD', 0),
    'monthly_budget_usd' => (float) env('AI_MONTHLY_BUDGET_USD', 0),
    'routing' => array_values(array_filter(array_map('trim', explode(',', (string) env('AI_PROVIDER_CHAIN', 'ollama,groq,gemini,openrouter,openai'))))),
    'embedding_provider' => env('AI_EMBEDDING_PROVIDER', 'ollama'),
    'providers' => [
        'ollama' => [
            'adapter' => OllamaProvider::class,
            'enabled' => env('OLLAMA_ENABLED', false),
            'base_url' => env('OLLAMA_BASE_URL', 'http://127.0.0.1:11434'),
            'api_key' => null,
            'model' => env('OLLAMA_MODEL'),
            'embedding_model' => env('OLLAMA_EMBEDDING_MODEL'),
            'cost_class' => 'local',
            'capabilities' => ['text_generation', 'structured_output', 'json_mode', 'embeddings'],
            'privacy_policy_url' => 'https://ollama.com/privacy',
            'data_retention_notes' => 'Self-hosted processing; retention is controlled by the operator and host configuration.',
            'recommended_for_private_data' => true,
            'last_verified' => '2026-08-21',
        ],
        'groq' => [
            'adapter' => GroqProvider::class,
            'enabled' => env('GROQ_ENABLED', false),
            'base_url' => 'https://api.groq.com/openai/v1',
            'api_key' => env('GROQ_API_KEY'),
            'model' => env('GROQ_MODEL'),
            'embedding_model' => null,
            'cost_class' => env('GROQ_COST_CLASS', 'free'),
            'capabilities' => ['text_generation', 'structured_output', 'json_mode', 'large_context'],
            'privacy_policy_url' => 'https://groq.com/privacy-policy/',
            'data_retention_notes' => 'Review the active Groq plan and data controls before sending learner content.',
            'recommended_for_private_data' => false,
            'last_verified' => '2026-08-21',
        ],
        'gemini' => [
            'adapter' => GeminiProvider::class,
            'enabled' => env('GEMINI_ENABLED', false),
            'base_url' => 'https://generativelanguage.googleapis.com/v1beta',
            'api_key' => env('GEMINI_API_KEY'),
            'model' => env('GEMINI_MODEL'),
            'embedding_model' => env('GEMINI_EMBEDDING_MODEL'),
            'cost_class' => env('GEMINI_COST_CLASS', 'free'),
            'capabilities' => ['text_generation', 'structured_output', 'json_mode', 'vision', 'embeddings', 'large_context'],
            'privacy_policy_url' => 'https://ai.google.dev/gemini-api/terms',
            'data_retention_notes' => 'Free-tier content may be used to improve Google products; do not route private journals by default.',
            'recommended_for_private_data' => false,
            'last_verified' => '2026-08-21',
        ],
        'openrouter' => [
            'adapter' => OpenRouterProvider::class,
            'enabled' => env('OPENROUTER_ENABLED', false),
            'base_url' => 'https://openrouter.ai/api/v1',
            'api_key' => env('OPENROUTER_API_KEY'),
            'model' => env('OPENROUTER_MODEL'),
            'embedding_model' => null,
            'cost_class' => env('OPENROUTER_COST_CLASS', 'free'),
            'capabilities' => ['text_generation', 'structured_output', 'json_mode', 'vision', 'large_context'],
            'privacy_policy_url' => 'https://openrouter.ai/privacy',
            'data_retention_notes' => 'Requests may be routed to third-party model hosts; review selected model/provider policies.',
            'recommended_for_private_data' => false,
            'last_verified' => '2026-08-21',
        ],
        'openai' => [
            'adapter' => OpenAiProvider::class,
            'enabled' => env('OPENAI_ENABLED', false),
            'base_url' => 'https://api.openai.com/v1',
            'api_key' => env('OPENAI_API_KEY'),
            'model' => env('OPENAI_MODEL'),
            'embedding_model' => env('OPENAI_EMBEDDING_MODEL'),
            'cost_class' => 'paid',
            'capabilities' => ['text_generation', 'structured_output', 'json_mode', 'vision', 'embeddings', 'large_context', 'reasoning'],
            'privacy_policy_url' => 'https://openai.com/policies/privacy-policy/',
            'data_retention_notes' => 'Optional paid provider. Review project data controls and retention settings.',
            'recommended_for_private_data' => false,
            'last_verified' => '2026-08-21',
        ],
    ],
];
